---
- name: Pull Docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    # - name: Pull server image
    #   docker_image:
    #     name: satvikvm/spe_main_project_server:latest
    #     source: pull
    # - name: Pull client image
    #   docker_image:
    #     name: satvikvm/spe_main_project_client:latest
    #     source: pull
    - name: Create new directory
      shell: mkdir -p spe_main_project_ansible
    - name: Copy Docker Compose
      copy:
        src: /home/satvik/Desktop/spe/repo/mern-social-media/docker-compose.yml
        dest: /home/satvik/spe_main_project_ansible/docker-compose.yml
    - name: Stop docker compose
      command: docker-compose down
      args:
        chdir: /home/satvik/spe_main_project_ansible
    - name: Get Docker Images
      command: docker images --format "{{.Repository}}:{{.Tag}}"
      register: docker_images
      changed_when: false
    - name: Delete Docker Images by Common String
      docker_image:
        name: "{{ item }}"
        state: absent
      loop: "{{ docker_images.stdout_lines }}"
      when: item.startswith('satvikvm')
    - name: Run docker compose
      command: docker-compose up -d
      args:
        chdir: /home/satvik/spe_main_project_ansible