---
- name: Pull Docker image of Calculator
  hosts: remote
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull server image
      docker_image:
        name: satvikvm/spe_main_project_server:latest
        source: pull
        force_source: yes
    - name: Pull client image
      docker_image:
        name: satvikvm/spe_main_project_client:latest
        source: pull
        force_source: yes
    - name: Create new directory
      shell: mkdir -p spe_main_project_ansible
    - name: Copy Docker Compose
      copy:
        src: /var/lib/jenkins/workspace/spe_main_project/docker-compose.yml
        dest: /home/satvik/spe_main_project_ansible/docker-compose.yml
    - name: Stop docker compose
      command: docker-compose down
      args:
        chdir: /home/satvik/spe_main_project_ansible
    - name: Run docker compose
      command: docker-compose up -d
      args:
        chdir: /home/satvik/spe_main_project_ansible
